jbossws/jbossws-cxf

- README
- modules/testsuite/cxf-tests/src/test/scripts/jbws-testsuite-default-config-tests.groovy
- modules/testsuite/cxf-tests/src/test/scripts/jbws-testsuite-default.groovy
- modules/testsuite/cxf-tests/src/test/scripts/jbws-testsuite-jms-wildfly1000.groovy
- modules/testsuite/cxf-tests/src/test/scripts/jbws-testsuite-jms-wildfly1010.groovy
- modules/testsuite/cxf-tests/src/test/scripts/jbws-testsuite-jms-wildfly901.groovy
- modules/testsuite/cxf-tests/src/test/scripts/jbws-testsuite-jms-wildfly902.groovy
- modules/testsuite/cxf-tests/src/test/scripts/jbws-testsuite-ssl-mutual-auth.groovy
- modules/testsuite/perf-tests/src/test/scripts/perf.groovy
- modules/testsuite/shared-tests/src/test/scripts/jbws-testsuite-shared-address-rewrite.groovy
- modules/testsuite/shared-tests/src/test/scripts/jbws-testsuite-shared-default-config-tests.groovy
- modules/testsuite/shared-tests/src/test/scripts/jbws-testsuite-shared-default.groovy
https://issues.jboss.org/browse/JBWS-3980
> [JBWS-3980] Make server logging to console optional for tests

- modules/addons/transports/http/undertow/src/test/java/org/jboss/wsf/stack/cxf/addons/transports/undertow/UndertowServerEngineTest.java
- modules/test-utils/src/main/java/org/jboss/wsf/test/AppclientHelper.java
- modules/test-utils/src/main/java/org/jboss/wsf/test/XOPTestSupport.java
https://issues.jboss.org/browse/JBWS-4039
Fixes in test code.
> [JBWS-4039] Fix code to not use default platform encoding

- modules/server/src/main/java/org/jboss/wsf/stack/cxf/configuration/ServerBeanCustomizer.java
- modules/testsuite/cxf-tests/src/test/java/org/jboss/test/ws/jaxws/cxf/jbws4046/DemoInterface.java
- modules/testsuite/cxf-tests/src/test/java/org/jboss/test/ws/jaxws/cxf/jbws4046/DemoServiceHandler.java
- modules/testsuite/cxf-tests/src/test/java/org/jboss/test/ws/jaxws/cxf/jbws4046/JBWS4046TestCase.java
- modules/testsuite/cxf-tests/src/test/java/org/jboss/test/ws/jaxws/cxf/jbws4046/v1/Demo.java
- modules/testsuite/cxf-tests/src/test/java/org/jboss/test/ws/jaxws/cxf/jbws4046/v2/Demo.java
- modules/testsuite/cxf-tests/src/test/resources/jaxws/cxf/jbws4046/WEB-INF/web.xml
- modules/testsuite/cxf-tests/src/test/resources/jaxws/cxf/jbws4046/handlers.xml
JIRA: https://issues.jboss.org/browse/JBWS-4046
This is a proposed fix for https://issues.jboss.org/browse/JBEAP-7742 
@asoldano could you review this please?
> JBWS-4046 PostConstruct method not invoked on web service handler

- modules/testsuite/pom.xml
https://issues.jboss.org/browse/JBWS-4102
This PR covers cases 4 and 5 from the issue
> [JBWS-4102] Get rid of some warnings during build

- .gitignore
- modules/testsuite/cxf-tests/src/test/scripts/jbws-testsuite-default-config-tests-elytron.groovy
- modules/testsuite/cxf-tests/src/test/scripts/jbws-testsuite-default-elytron.groovy
- modules/testsuite/shared-tests/src/test/scripts/jbws-testsuite-shared-default-config-tests-elytron.groovy
- modules/testsuite/shared-tests/src/test/scripts/jbws-testsuite-shared-default-elytron.groovy
Otherwise scripts fails on `IndexOutOfBoundsException: Index: 5, Size: 4`.
(+ auto-generated lib directory into .gitignore)
> Fix of groovy scripts for current default undertow subsystem configuration

- modules/client/src/main/java/org/jboss/wsf/stack/cxf/tools/CXFConsumerImpl.java
https://issues.jboss.org/browse/JBWS-4111
Use try-with-resources for properly handle closing of streams in all cases.
> [JBWS-4111] Ensure streams are closed

- modules/client/pom.xml
- modules/client/src/main/java/org/jboss/wsf/stack/cxf/Loggers.java
- modules/client/src/main/java/org/jboss/wsf/stack/cxf/Messages.java
- modules/client/src/main/java/org/jboss/wsf/stack/cxf/tools/CXFConsumerImpl.java
- modules/client/src/main/java/org/jboss/wsf/stack/cxf/tools/JBossModulesAwareCompiler.java
- modules/client/src/main/java/org/jboss/wsf/stack/cxf/tools/JavaFileObjectImpl.java
- modules/client/src/main/java/org/jboss/wsf/stack/cxf/tools/Jdk9PlusJBossModulesAwareCompiler.java
- modules/resources/src/main/resources/modules/wildfly1010/org/jboss/ws/jaxws-client/main/module.xml
- modules/resources/src/main/resources/modules/wildfly1100/org/jboss/ws/jaxws-client/main/module.xml
- modules/resources/src/main/resources/modules/wildfly1200/org/jboss/ws/jaxws-client/main/module.xml
- modules/resources/src/main/resources/modules/wildfly1300/org/jboss/ws/jaxws-client/main/module.xml
- modules/testsuite/shared-tests/src/test/java/org/jboss/test/ws/jaxws/smoke/tools/WSConsumerPlugin.java
- pom.xml
> [JBWS-4107]

- modules/addons/pom.xml
- modules/addons/transports/http/undertow/src/main/java/org/jboss/wsf/stack/cxf/addons/transports/undertow/UndertowServerDestination.java
- modules/addons/transports/http/undertow/src/main/java/org/jboss/wsf/stack/cxf/addons/transports/undertow/UndertowServerEngine.java
- modules/addons/transports/http/undertow/src/main/java/org/jboss/wsf/stack/cxf/addons/transports/undertow/UndertowServerEngineFactory.java
- modules/addons/transports/udp/src/main/java/org/jboss/wsf/stack/cxf/addons/transports/udp/UDPConduit.java
- modules/addons/transports/udp/src/main/java/org/jboss/wsf/stack/cxf/addons/transports/udp/UDPDestination.java
- modules/addons/transports/udp/src/main/java/org/jboss/wsf/stack/cxf/addons/transports/udp/UDPTransportFactory.java
- modules/resources/src/main/resources/modules/wildfly1010/org/jboss/ws/cxf/jbossws-cxf-transports-udp/main/module.xml
- modules/resources/src/main/resources/modules/wildfly1010/org/jboss/ws/cxf/jbossws-cxf-transports-undertow/main/module.xml
- modules/resources/src/main/resources/modules/wildfly1100/org/jboss/ws/cxf/jbossws-cxf-transports-udp/main/module.xml
- modules/resources/src/main/resources/modules/wildfly1100/org/jboss/ws/cxf/jbossws-cxf-transports-undertow/main/module.xml
- modules/resources/src/main/resources/modules/wildfly1200/org/jboss/as/webservices/server/integration/main/module.xml
- modules/resources/src/main/resources/modules/wildfly1200/org/jboss/ws/cxf/jbossws-cxf-transports-udp/main/module.xml
- modules/resources/src/main/resources/modules/wildfly1200/org/jboss/ws/cxf/jbossws-cxf-transports-undertow/main/module.xml
- modules/resources/src/main/resources/modules/wildfly1300/org/jboss/ws/cxf/jbossws-cxf-transports-udp/main/module.xml
- modules/resources/src/main/resources/modules/wildfly1300/org/jboss/ws/cxf/jbossws-cxf-transports-undertow/main/module.xml
- modules/server/src/main/java/org/jboss/wsf/stack/cxf/security/authentication/SubjectCreatingInterceptor.java
Jira: https://issues.jboss.org/browse/JBEAP-4607
Some classes have also Java logger to fulfill CXF API contract.
> [JBEAP-4607] jbossws-cxf is using cxf based logging instead of org.jboss.logging.Logger in some places

- modules/server/src/main/java/org/jboss/wsf/stack/cxf/security/authentication/callback/UsernameTokenCallback.java
Jira: https://issues.jboss.org/browse/JBEAP-4730
> [JBEAP-4730] jbossws-common contains own Base64 implementation

- modules/dist/src/main/scripts/assembly-test-server.xml
https://issues.jboss.org/browse/JBWS-4126
> [JBWS-4126] System-specific file separator in assembly script

- .travis-settings.xml
- .travis.yml
Test with JDK11 on Travis CI
https://issues.jboss.org/browse/JBWS-4140
> [JBWS-4140] Test with JDK11 on Travis CI

- modules/testsuite/perf-tests/pom.xml
- modules/testsuite/pom.xml
- pom.xml
https://issues.jboss.org/browse/JBWS-4152
Extract versions to properties where possible.
> [JBWS-4152] Extract versions to properties

- modules/addons/transports/http/undertow/pom.xml
- modules/addons/transports/udp/pom.xml
- modules/client/pom.xml
- modules/jaspi/pom.xml
- modules/server/pom.xml
- modules/testsuite/pom.xml
- pom.xml
https://issues.jboss.org/browse/JBWS-4151
Dependency management in root pom.xml contains many exclusions yet some of them are no longer needed. This PR tries to update the set of needed exclusions. This is done mostly by removing exclusions not needed anymore but there were also situations where managed dependency with exclusions in dependencyManagement is declared with different/additional set of exclusions in child pom.
> [JBWS-4151] Review dependency management

- modules/server/pom.xml
- modules/testsuite/pom.xml
- pom.xml
https://issues.jboss.org/browse/JBWS-4157
Move to EJB API 3.2 to be synced with current WildFly
> [JBWS-4157] Move to EJB API 3.2 to be synced with WildFly

- modules/test-utils/pom.xml
- modules/testsuite/cxf-tests/src/test/java/org/jboss/test/ws/jaxws/samples/wsse/policy/jaas/UsernameAuthorizationDigestEjbTestCase.java
https://issues.jboss.org/browse/JBWS-4181
Clean up some old workarounds not needed anymore.
> [JBWS-4181] Remove TS workarounds

- README.md
@jimma this is just few enhancement to better readability and few fixed typos
> Update README.md - formatting and typos

- modules/test-utils/src/main/java/org/jboss/wsf/test/IgnoreJdk.java
- modules/testsuite/cxf-tests/src/test/java/org/jboss/test/ws/jaxws/samples/wsse/policy/basic/SignEncryptGCMTestCase.java
https://issues.jboss.org/browse/JBWS-4186
Add IgnoreJdk rule to skip the particular tests for particular JDK.
> [JBWS-4186] Ignore the test due to JBEAP-5200

- modules/client/src/main/java/org/jboss/wsf/stack/cxf/client/serviceref/CXFHandlerResolverImpl.java
- pom.xml
https://issues.redhat.com/browse/JBWS-4219
> [JBWS-4219] Implemented support for Jakarta EE9 namespace handling of handler chain DDs

- pom.xml
https://issues.redhat.com/browse/JBWS-4220
> [JBWS-4220]:Upgrade apache cxf to 3.3.10

- modules/testsuite/pom.xml
- pom.xml
... and enabling passing tests
> Elytron 2 upgrade

- docbook/src/main/doc/adoc/content/chapter-4-JAX_WS_Tools.adoc
https://issues.redhat.com/browse/JBWS-4324
> [JBWS-4324] Fixing code of jax-ws client

- modules/server/src/main/java/org/jboss/wsf/stack/cxf/security/authentication/SubjectCreator.java
https://issues.redhat.com/browse/JBWS-4335
> [JBWS-4335] Use PicketBox to obtain Subject when Elytron security realm exposes PicketBox security domain

- modules/server/src/main/java/org/jboss/wsf/stack/cxf/security/authentication/SubjectCreator.java
https://issues.redhat.com/browse/JBWS-4344
> [JBWS-4344] Avoid possible NPE in SubjectCreator when elytron realm is used

- modules/client/src/main/java/org/jboss/wsf/stack/cxf/client/ProviderImpl.java
https://issues.redhat.com/browse/JBWS-4445
> [JBWS-4445] Implementing ports cache for service instances

- modules/client/src/main/java/org/jboss/wsf/stack/cxf/client/TCCLAwareHandlerReplacer.java
- modules/client/src/main/java/org/jboss/wsf/stack/cxf/client/TCCLAwareLogicalHandler.java
- modules/client/src/main/java/org/jboss/wsf/stack/cxf/client/TCCLAwareSOAPHandler.java
https://issues.redhat.com/browse/JBWS-4444
> [JBWS-4444] There must be distinguishion between Logical and SOAP handlers during the delegation process

- modules/testsuite/cxf-tests/src/test/java/org/jboss/test/ws/jaxws/cxf/jms/JMSEndpointAPITestCase.java
- modules/testsuite/cxf-tests/src/test/java/org/jboss/test/ws/jaxws/cxf/jms/JMSEndpointOnlyDeploymentTestCase.java
- modules/testsuite/cxf-tests/src/test/java/org/jboss/test/ws/jaxws/cxf/jms_http/JMSHTTPEndpointDeploymentTestCase.java
- pom.xml
https://issues.redhat.com/browse/JBWS-4448
> [JBWS-4448] Upgrade Apache CXF to 4.0.9 (including dependencies)

- modules/client/src/main/java/org/jboss/wsf/stack/cxf/client/ProviderImpl.java
Improvements to the ports cache mechanism:
* From now on, the cache is always updated atomically
https://issues.redhat.com/browse/JBWS-4450
https://issues.redhat.com/browse/JBWS-4445
> [JBWS-4445][JBWS-4450] Improvements to the ports cache mechanism:
